### ISSUE TITLE
请教：

### ISSUE THREAD

**Issue by litianc** [toxotguo/thinking#1]
智能合约的设计模式和升级方法，写得很棒！写出有这样的总结非一日之功！
同时，我有两个问题请教：
1. 这样的“智能合约的生命周期”设计有何出处和参考文献？我想多学习智能合约深层次的技术，如果文章有“参考文献”我能顺藤摸瓜学到更多。
2. 数据迁移的摩尔根树迁移法，简短内容无法让我真正明白其做法，经搜索“smart contract merkle tree migration”没有得到想要的资料。能否像“控制器合约、数据合约”那样解释得详细一点或者给点学习资料。

**Comment by toxotguo** [comment]
@litianc 谢谢你的关注。

**Comment by toxotguo** [comment]
@litianc 谢谢你的关注。
1. 文章的内容基本都是过去一段时间个人和所在团队在区块链底层平台开发研究和区块链智能合约应用的的工程实践上的一些经验总结，并无对应参考文献。
2. 默克尔树迁移法是基于对以太坊底层核心的深刻理解研究出来的一个解决方案。也属于业界首创，业界目前并无先例，所以并不能通过搜索引擎来搜到对应的内容。具体的实现方案上也较为复杂，需要对以太坊底层核心有足够的了解才能解释清楚。因此就不在这里展开。后续具体的实现会在https://github.com/bcosorg/bcos上实现并开源，可以关注。
欢迎多交流。

**Comment by litianc** [comment]
Cool！我会关注的，谢谢

**Comment by litianc** [comment]
@toxotguo 谢谢
