### ISSUE TITLE
启动raiden的时候报错

### ISSUE THREAD

**Issue by ethshan** [toxotguo/thinking#2]
Traceback (most recent call last):
  File "/tmp/.mount_GjUdir/usr/bin//raiden", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

ubuntu 版本16 server版 64位
完全按照流程操作。唯一的问题是，testnet尚未完全同步。求大神指点一下问题出在哪。多谢

**Comment by toxotguo** [comment]
@ethshan 看起来像是python环境没有装好，把pip、setuptools这些都卸载重装试试。

**Comment by toxotguo** [comment]
@ethshan http://raiden-network.readthedocs.io/en/stable/overview_and_guide.html#introduction 供参考

**Comment by panlin-go** [comment]
合约升级  默克尔树 迁移法 原理是怎样的啊？ 哪里有资料？

**Comment by toxotguo** [comment]
@panlin-go 
文章中有原理性描述，无其他资料。  [浅谈以太坊智能合约的设计模式与升级方法](https://github.com/toxotguo/thinking/blob/master/%E6%B5%85%E8%B0%88%E4%BB%A5%E5%A4%AA%E5%9D%8A%E6%99%BA%E8%83%BD%E5%90%88%E7%BA%A6%E7%9A%84%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%8D%87%E7%BA%A7%E6%96%B9%E6%B3%95.md)
